2022-02-10 10:08:46,189 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-1' coro=<Kernel.poll_control_queue() running at E:\anaconda\envs\python38_spy5\lib\site-packages\ipykernel\kernelbase.py:227> wait_for=<Future finished result=<Future at 0x...state=pending>> cb=[_chain_future.<locals>._call_set_state() at E:\anaconda\envs\python38_spy5\lib\asyncio\futures.py:367]>
